id: csharp-mcp-development
name: C# MCP Server Development
description: Complete toolkit for building Model Context Protocol (MCP) servers in C# using the official SDK. Includes instructions for best practices, a prompt for generating servers, and an expert chat mode for guidance.
tags: [csharp, mcp, model-context-protocol, dotnet, server-development]
items:
  - path: instructions/csharp-mcp-server.instructions.md
    kind: instruction
  - path: prompts/csharp-mcp-server-generator.prompt.md
    kind: prompt
  - path: chatmodes/csharp-mcp-expert.chatmode.md
    kind: chat-mode
    usage: |
      recommended

      This chat mode provides expert guidance for building MCP servers in C#.

      This chat mode is ideal for:
      - Creating new MCP server projects
      - Implementing tools and prompts
      - Debugging protocol issues
      - Optimizing server performance
      - Learning MCP best practices

      To get the best results, consider:
      - Using the instruction file to set context for all Copilot interactions
      - Using the prompt to generate initial project structure
      - Switching to the expert chat mode for detailed implementation help
      - Providing specific details about what tools or functionality you need

display:
  ordering: manual
  show_badge: true
